program: src.fine_tune.fine_tune_yolo
project: "YOLO_FineTune_Sweep_augs"
method: grid
metric:
  name: val_coco_ap
  goal: maximize
parameters:
  epochs:
    value: 25
  freeze:
    values: [22]
  lr:
    values: [0.00001]
  aug_strategy:
    values: ["composite_only"]
command:
  - ${env}
  - ${interpreter}
  - "-m"
  - ${program}
  - "--config"
  - "src/fine_tune/configs/single_run/config_yolo_base.yaml"
  - ${args}
