model:
  encoder: "resnet18"

training:
  epochs: 50
  batch_size: 128
  lr: 0.0005
  scheduler: "plateau"
  num_workers: 4

data:
  mode: "search"

project: "C5-ImageCaptioning"
output_dir: "results/baseline"
