program: train.py
project: "C5-ImageCaptioning-sweep-text-level"
method: grid
metric:
  name: best_METEOR
  goal: maximize

parameters:
  encoder:
    value: "clip-vit-b32"
  text_level:
    values: ["word", "subword"]
  decoder_setup:
    values: ["lstm-3", "gru-2"]
  decoder_dim:
    value: 1024
  embed_dim:
    value: 1024
  lr:
    value: 0.0005
  mode:
    value: "search"
  epochs:
    value: 10
  batch_size:
    value: 128
  num_workers:
    value: 4
  output_dir:
    value: "results/text_level_sweep"
  freeze_encoder:
    value: true

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
