program: train.py
project: "C5-ImageCaptioning"
method: grid
metric:
  name: METEOR
  goal: maximize
parameters:
  encoder:
    values: ["resnet18", "resnet34", "resnet50", "vgg16", "vgg19", "efficientnet_b0"]
  mode:
    value: "search"
  epochs:
    value: 10
  batch_size:
    value: 128
  lr:
    value: 5e-4
  num_workers:
    value: 4
  output_dir:
    value: "results/checkpoints"
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
