project: "kitti-mots-yolo-sweep"
output_dir: "results"
experiment_name: "yolo_sweep"

data:
  root: "/ghome/group01/mcv/datasets/C5/KITTI-MOTS/"
  mode: "full"
  seed: 42
  split_ratio: 0.8

model:
  name: "yolo"
  weights: "yolov10b.pt"

training:
  imgsz: 640
  batch_size: 16
  # No "stages" defined -> The script will run 1 stage based on cli arguments
  epochs: 25  # Will be overridden by sweep "epochs: 25" argument
  lr: 0.001   # Will be overridden by sweep 
  freeze: 0   # Will be overridden by sweep
  conf: 0
  nms_iou_threshold: 0.5
  aug_strategy: "base"
  log_images_every: 25
